on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"
  - cron: "0 12 * * *"
  - cron: "0 13 * * *"
  - cron: "0 14 * * *"
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: pip install requests
      - run: python ICAO.py
        env:
          lc: ${{ secrets.lc }}
          tk: ${{ secrets.tk }}
          WXPusherAppToken: ${{ secrets.WXPusherAppToken }}
          WXPusherUIDS: ${{ secrets.WXPusherUIDS }}
          EXAMDATE: ${{ secrets.EXAMDATE }}
